reddit_clone/reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy]
  resources :posts, except: [:index]

end

reddit_clone/reddit_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reddit_clone/reddit_clone/app/models/post.rb
class Post < ApplicationRecord
  validates :title, :url, presence: true

  belongs_to :sub,
  foreign_key: :sub_id,
  class_name: :Sub

  belongs_to :user,
  foreign_key: :user_id,
  class_name: :User

end

reddit_clone/reddit_clone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :bigint(8)        not null, primary key
#  title       :string           not null
#  description :text             not null
#  user_id     :integer          not null
#

class Sub < ApplicationRecord
  validates :description, presence: true
  validates :title, presence: true, uniqueness: true

  belongs_to :user,
  foreign_key: :user_id,
  class_name: :User

  has_many :posts,
  foreign_key: :sub_id,
  class_name: :Post 
end

reddit_clone/reddit_clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord

  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}

  attr_reader :password
  before_validation :ensure_session_token

  has_many :subs,
  foreign_key: :user_id,
  class_name: :Sub

  has_many :post,
  foreign_key: :user_id,
  class_name: :Post

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
end

reddit_clone/reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login(user)
    session[:session_token] = user.reset_session_token!
  end

  def logged_in?
    current_user.nil? ? false : true
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end
end

reddit_clone/reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    # @post = Post.new
    @subs = Sub.all
    render :new
  end

  def create
    post = Post.new(post_params)
    post.user_id = current_user.id
    if post.save
      redirect_to post_url(post)
    else
      flash.now[:errors] = post.errors.full_messages
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end


  def post_params
    params.require(:post).permit(:title, :url, :content, :sub_id)
  end


end

reddit_clone/reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:username], params[:user][:password])

    if user.save
      login(user)
      redirect_to subs_url
    else
      flash.now[:errors] = ["Invalid Credentials"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end

end

reddit_clone/reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :ensure_moderator, only: [:edit, :update]

  def new
    render :new
  end

  def create
    sub = Sub.new(sub_params)
    sub.user_id = current_user.id
    if sub.save
      redirect_to sub_url(sub)
    else
      flash.now[:errors] = sub.errors.full_messages
      render :new
    end
  end

  def show
    @sub = Sub.find_by(id: params[:id])
    render :show
  end

  def index
    @subs = Sub.all
    render :index
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
    render :edit
  end

  def update
    @sub = Sub.find_by(id: params[:id])

    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

private
  def ensure_moderator
    @sub = Sub.find_by(id: params[:id])
    unless @sub.user_id == current_user.id
      flash[:errors] = ["You are not a moderator!"]
      redirect_to subs_url
    end
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

end

reddit_clone/reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.new(user_params)
    if user.save
      login(user)
      redirect_to subs_url
    else
      flash.now[:errors] = user.errors.full_messages
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

reddit_clone/reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit_clone/reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

reddit_clone/reddit_clone/app/helpers/sessions_helper.rb
module SessionsHelper
end

reddit_clone/reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

reddit_clone/reddit_clone/app/helpers/users_helper.rb
module UsersHelper
end

reddit_clone/reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

reddit_clone/reddit_clone/app/views/posts/new.html.erb
<h1>NEW POST!</h1>

<form action="<%= posts_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>
    Title:
    <input type="text" name="post[title]" value="">
  </label>

  <label>
    URL:
    <input type="text" name="post[url]" value="">
  </label>

  <label>
    Content:
    <textarea name="post[content]" rows="8" cols="80"> </textarea>
  </label>

  <% @subs.each do |sub| %>
    <input type="checkbox" name="post[sub_id][]" value="<%= sub.id %>">
    <%= sub.title %>
    <br>
    <% end %>

    <input type="submit" name="" value="Submit">
</form>

reddit_clone/reddit_clone/app/views/subs/edit.html.erb
<h1>EDIT SUB</h1>

<form action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="patch">
  <label>
    Title:
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <label>
    Description:
    <textarea name="sub[description]" rows="8" cols="80"> <%= @sub.description %></textarea>
  </label>

  <input type="submit" value="Submit!">
</form>

reddit_clone/reddit_clone/app/views/subs/index.html.erb
<h1>ALL THE SUBS! </h1>

<% @subs.each do |sub|  %>
  <li>
    <a href="<%= sub_url(sub) %>">
      <%= sub.title  %>
    </a>
  </li>
<% end %>

reddit_clone/reddit_clone/app/views/subs/new.html.erb
<h1>CREATE A NEW SUB</h1>

<form action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>
    Title:
    <input type="text" name="sub[title]" value="">
  </label>

  <label>
    Description:
    <textarea name="sub[description]" rows="8" cols="80"></textarea>
  </label>

  <input type="submit" value="Submit!">
</form>

reddit_clone/reddit_clone/app/views/subs/show.html.erb
<h1> <%= @sub.title %> </h1>

<h3> Description </h3>
<h4> <%= @sub.description %> </h4>

reddit_clone/reddit_clone/app/views/users/new.html.erb
"SIGN UP!"

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<label>
  Username
  <input type="text" name="user[username]" value="">
</label>
<label>
  Password
  <input type="password" name="user[password]" value="">
</label>

<input type="submit" value="Sign-Up">
  <% if flash.now[:errors] %>
  <% flash.now[:errors].each do |error| %>
  <%= error %>
  <% end %>
  <% end %>
</form>